[deps]
# AmplNLWriter = "7c4d4715-977e-5154-bfe0-e096adeac482"
# BinaryWrappers = "f01c122e-0ea1-4f85-ad8f-907073ad7a9f"
# Bonmin_jll = "29cba6d7-6840-5cf2-a2fa-9bdfccfe29ea"
# Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
# Couenne_jll = "f09e9e23-9010-5c9e-b679-9f1d8f79b85c"
# DWave = "4d534982-bf11-4157-9e48-fe3a62208a50"
# DWaveNeal = "870cdf72-5502-4b10-839c-127ceab78f22"
# GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
# GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
# Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
# HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
# Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
# JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
# Karnak = "cd156443-31ad-4f6f-850f-a93ee5f75905"
# LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
# Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
# PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
# PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
# QUBO = "ce8c2e91-a970-4681-856b-16178c24a30c"
# SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
# StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
# StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
# lib4ti2_jll = "1493ae25-0f90-5c0e-a06c-8c5077d6d66f"
